cms_blog_index:
    path:     /
    defaults: { _controller: "dcContentBundle:Blog:index" }
    methods:  GET

cms_blog_show:
    path:     /{id}/show
    defaults: { _controller: "dcContentBundle:Blog:show" }
    methods:  GET

cms_blog_new:
    path:     /new
    defaults: { _controller: "dcContentBundle:Blog:new" }
    methods:  [GET, POST]

cms_blog_edit:
    path:     /{id}/edit
    defaults: { _controller: "dcContentBundle:Blog:edit" }
    methods:  [GET, POST]

cms_blog_delete:
    path:     /{id}/delete
    defaults: { _controller: "dcContentBundle:Blog:delete" }
    methods:  DELETE
